In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
nestedlist = [[1,2,], [3,4], [5,6]]

In [7]:
nestedlist

[[1, 2], [3, 4], [5, 6]]

In [8]:
np.array(nestedlist)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,21,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(3,4)

array([[0.24761591, 0.38826791, 0.75931356, 0.73971131],
       [0.12266754, 0.60681893, 0.55420417, 0.88175538],
       [0.66522875, 0.81410258, 0.26499296, 0.05585057]])

In [25]:
np.random.randn(5,5)

array([[ 0.27364993, -0.99038591,  0.60394274,  1.39281399,  1.8869862 ],
       [ 1.9971805 , -1.22472098,  0.78426557,  0.66714483,  0.56247417],
       [-0.52474077,  1.34444329, -0.21683178, -1.05717286, -0.48403322],
       [ 1.17331921,  0.27287958, -1.39937051, -0.62965454, -0.78235409],
       [ 1.72079009,  0.32565883, -0.09279125, -0.87341513,  0.47904513]])

In [28]:
np.random.randint(1,100, (2,3))

array([[27, 12, 54],
       [20, 88, 44]])

In [29]:
np.random.seed(42)

In [30]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [34]:
ranarr.shape

(10,)

In [44]:
x = ranarr.reshape(5,2)
x

array([[38, 18],
       [22, 10],
       [10, 23],
       [35, 39],
       [23,  2]])

In [36]:
ranarr.argmin()

9

In [37]:
ranarr.argmax()

7

In [38]:
ranarr.dtype

dtype('int64')

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[-3:]

array([ 8,  9, 10])

In [42]:
ranarr.shape

(10,)

In [45]:
x

array([[38, 18],
       [22, 10],
       [10, 23],
       [35, 39],
       [23,  2]])

In [46]:
x[1,1]

10

In [47]:
x[:2]

array([[38, 18],
       [22, 10]])

In [50]:
x[1,0:]

array([22, 10])

In [52]:
x[x>25]

array([38, 35, 39])

In [53]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [56]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
arr2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [58]:
arr2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])