In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

import os

%matplotlib inline

import tensorflow as tf

In [2]:
path_to_file = '/Users/Bryan/Documents/Programming/Python_Courses/Tensorflow2/06-NLP-and-Text-Data/shakespeare.txt'

In [3]:
text = open(path_to_file, 'r').read()

In [4]:
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [5]:
# print reflects the \n character

print(text[4500:4800])

converted are
  From his low tract and look another way:
    So thou, thy self out-going in thy noon:
    Unlooked on diest unless thou get a son.


                     8
  Music to hear, why hear'st thou music sadly?
  Sweets with sweets war not, joy delights in joy:
  Why lov'st thou that which t


In [6]:
print(text[140500:141500])

reward.
  HELENA. Inspired merit so by breath is barr'd.
    It is not so with Him that all things knows,
    As 'tis with us that square our guess by shows;
    But most it is presumption in us when
    The help of heaven we count the act of men.
    Dear sir, to my endeavours give consent;
    Of heaven, not me, make an experiment.
    I am not an impostor, that proclaim  
    Myself against the level of mine aim;
    But know I think, and think I know most sure,
    My art is not past power nor you past cure.
  KING. Art thou so confident? Within what space
    Hop'st thou my cure?
  HELENA. The greatest Grace lending grace.
    Ere twice the horses of the sun shall bring
    Their fiery torcher his diurnal ring,
    Ere twice in murk and occidental damp
    Moist Hesperus hath quench'd his sleepy lamp,
    Or four and twenty times the pilot's glass
    Hath told the thievish minutes how they pass,
    What is infirm from your sound parts shall fly,
    Health shall live free, and s

In [7]:
# get all the unique characters

vocab = sorted(set(text))
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [8]:
len(vocab)

84

# Text Processing

In [9]:
# assign numbers to each item in the list

for pair in enumerate(vocab):
    print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [10]:
# use dictionary comprehension note using {} rather than []

char_to_ind = {char: ind for ind, char in enumerate(vocab)}
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [11]:
char_to_ind['H']

33

In [12]:
ind_to_char = np.array(vocab)
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '|', '}'], dtype='<U1')

In [13]:
ind_to_char[33]

'H'

In [14]:
# encode text to integers

encoded_text = np.array([char_to_ind[c] for c in text])

In [15]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [16]:
encoded_text.shape

(5445609,)

In [17]:
sample = text[:500]
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [18]:
# create batches and sequence size

line = 'From fairest creatures we desire increase'

In [19]:
len(line)

41

In [20]:
lines = '''
From fairest creatures we desire increase,
That thereby beauty's rose might never die,
But as the riper should by time decease
'''

In [21]:
len(lines)

128

In [22]:
# need sequence long enough to pick up structure
# set the batch size to 120 chars

seq_len = 120

In [23]:
# get the total number of sequences
# use the // to round

total_num_seq = len(text) // (seq_len+1)
total_num_seq

45005

In [24]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [25]:
type(char_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [26]:
for item in char_dataset.take(500):
    print(item.numpy())

0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
12
0
1
1
31
73
70
68
1
61
56
64
73
60
74
75
1
58
73
60
56
75
76
73
60
74
1
78
60
1
59
60
74
64
73
60
1
64
69
58
73
60
56
74
60
8
0
1
1
45
63
56
75
1
75
63
60
73
60
57
80
1
57
60
56
76
75
80
5
74
1
73
70
74
60
1
68
64
62
63
75
1
69
60
77
60
73
1
59
64
60
8
0
1
1
27
76
75
1
56
74
1
75
63
60
1
73
64
71
60
73
1
74
63
70
76
67
59
1
57
80
1
75
64
68
60
1
59
60
58
60
56
74
60
8
0
1
1
33
64
74
1
75
60
69
59
60
73
1
63
60
64
73
1
68
64
62
63
75
1
57
60
56
73
1
63
64
74
1
68
60
68
70
73
80
21
0
1
1
27
76
75
1
75
63
70
76
1
58
70
69
75
73
56
58
75
60
59
1
75
70
1
75
63
64
69
60
1
70
78
69
1
57
73
64
62
63
75
1
60
80
60
74
8
0
1
1
31
60
60
59
5
74
75
1
75
63
80
1
67
64
62
63
75
5
74
1
61
67
56
68
60
1
78
64
75
63
1
74
60
67
61
9
74
76
57
74
75
56
69
75
64
56
67
1
61
76
60
67
8
0
1
1
38
56
66
64
69
62
1
56
1
61
56
68
64
69
60
1
78
63
60
73
60
1
56
57
76
69
59
56
69
58
60
1
67
64
60
74
8
0
1
1
45
63
80
1
74
60
67
61
1
75
63
80
1
61
70
60
8
1
75
70
1
75
63


In [27]:
# view the text

for item in char_dataset.take(500):
    print(ind_to_char[item.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


In [28]:
# create sequences
# used the // to remove remainder

sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

In [29]:
def create_seq_targets(seq):
    # input text is from beginning to second to last char
    input_txt = seq[:-1] # Hello my nam
    
    # target text is shifted one forward
    target_txt = seq[1:] # ello my name
    return input_txt, target_txt

In [30]:
# map it to all the sequences

dataset = sequences.map(create_seq_targets)

In [31]:
# string look similar, but the begining of the first starts with 0, end of second ends with a 1 whitespace

for input_txt, target_txt in dataset.take(1):
    print(input_txt.numpy())
    print("".join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    print("".join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [32]:
batch_size = 128

In [33]:
# set a chunk size for memory issues
# yields 128 sequences of 120 chars


buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

# Create the Model

In [34]:
vocab_size = len(vocab)
vocab_size

84

In [35]:
# pick something similar to vocab scale

embed_dim = 64

In [36]:
rnn_neurons = 1026

In [37]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [38]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module tensorflow.python.keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    Args:
      y_true: Ground truth values.
      y_pred: The predicted values.
      from_logits: Whether `y_pred` is expected to be a logits tensor. By default,
        we assume that `y_pred` encodes a probability distribution.
      axis: (Optional) Defaults to -1. The dimension along which the entropy is
        computed.
    
    Returns:
      Sparse categorical crossentropy loss value.



In [39]:
# change from_logits due to one hot encoding

def sparse_cat_loss(y_true, y_pred):
    return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [40]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GRU, Embedding
from tensorflow.keras.models import load_model

In [41]:
def create_model(vocab_size,embed_dim, rnn_neurons, batch_size):
    
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim, batch_input_shape=[batch_size,None]))
    model.add(GRU(rnn_neurons,
                  return_sequences=True,
                  stateful=True,
                  recurrent_initializer='glorot_uniform'))
    model.add(Dense(vocab_size))
    
    model.compile('adam', loss=sparse_cat_loss)
    
    return model

In [42]:
model = create_model(vocab_size=vocab_size,
                    embed_dim=embed_dim,
                    rnn_neurons=rnn_neurons,
                    batch_size=batch_size)

In [43]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 64)           5376      
_________________________________________________________________
gru (GRU)                    (128, None, 1026)         3361176   
_________________________________________________________________
dense (Dense)                (128, None, 84)           86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [44]:
import plaidml.keras
plaidml.keras.install_backend()
from keras import backend as K

In [45]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)

In [46]:
example_batch_predictions.shape

TensorShape([128, 120, 84])

In [47]:
# output is probabilities for characters
example_batch_predictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[-0.00723036,  0.0020071 , -0.00401948, ..., -0.00070471,
         0.00668725, -0.00382433],
       [-0.00192457, -0.00358631, -0.00235842, ..., -0.00031148,
         0.00651901, -0.00259872],
       [ 0.00085488, -0.00348588,  0.00118352, ...,  0.00333172,
         0.00043161, -0.00104413],
       ...,
       [-0.00261033, -0.00119531,  0.00195659, ..., -0.00539637,
        -0.00124454,  0.00225427],
       [-0.00503391,  0.00322086,  0.01281119, ..., -0.00409464,
         0.00019547,  0.0041295 ],
       [ 0.00435675,  0.00634694,  0.00584233, ..., -0.0083868 ,
        -0.00196448,  0.00425379]], dtype=float32)>

In [48]:
sample_indices = tf.random.categorical(example_batch_predictions[0], num_samples = 1)
sample_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[56],
       [65],
       [65],
       [ 5],
       [24],
       [47],
       [16],
       [60],
       [72],
       [41],
       [32],
       [44],
       [20],
       [67],
       [47],
       [66],
       [42],
       [31],
       [73],
       [15],
       [ 2],
       [67],
       [41],
       [57],
       [ 7],
       [52],
       [52],
       [13],
       [69],
       [48],
       [21],
       [20],
       [53],
       [ 9],
       [79],
       [66],
       [25],
       [83],
       [66],
       [26],
       [23],
       [28],
       [70],
       [35],
       [ 6],
       [66],
       [79],
       [39],
       [46],
       [11],
       [28],
       [68],
       [65],
       [27],
       [39],
       [72],
       [67],
       [35],
       [41],
       [73],
       [ 2],
       [56],
       [19],
       [51],
       [70],
       [ 2],
       [40],
       [23],
       [ 2],
       [73],
       [60],
       [60],
       [44],
   

In [49]:
# reshape

sample_indices = tf.squeeze(sample_indices, axis = -1).numpy()

In [50]:
# pass to ind to char

ind_to_char[sample_indices]

array(['a', 'j', 'j', "'", '>', 'V', '5', 'e', 'q', 'P', 'G', 'S', '9',
       'l', 'V', 'k', 'Q', 'F', 'r', '4', '!', 'l', 'P', 'b', ')', '[',
       '[', '2', 'n', 'W', ':', '9', ']', '-', 'x', 'k', '?', '}', 'k',
       'A', '<', 'C', 'o', 'J', '(', 'k', 'x', 'N', 'U', '0', 'C', 'm',
       'j', 'B', 'N', 'q', 'l', 'J', 'P', 'r', '!', 'a', '8', 'Z', 'o',
       '!', 'O', '<', '!', 'r', 'e', 'e', 'S', 'W', 'f', '2', '|', '9',
       ']', '<', 'B', 'E', '}', ':', 'c', 'Y', '|', 'k', 'f', 'D', '3',
       '}', 'Q', ':', 'm', ',', 'f', 'V', '`', 'Z', 'L', 'S', ';', ',',
       ';', '7', '8', 'y', 'I', 't', 'w', '7', 'M', 'h', '3', '6', '9',
       '(', '9', 'P'], dtype='<U1')

## Run Model

In [ ]:
epochs = 50
model.fit(dataset, epochs=epochs)

Epoch 1/50
351/351 [==============================] - 1994s 6s/step - loss: 2.5183
Epoch 2/50
351/351 [==============================] - 1767s 5s/step - loss: 1.7237
Epoch 3/50
351/351 [==============================] - 1871s 5s/step - loss: 1.4591
Epoch 4/50
351/351 [==============================] - 1884s 5s/step - loss: 1.3396
Epoch 5/50
351/351 [==============================] - 1824s 5s/step - loss: 1.2762
Epoch 6/50
351/351 [==============================] - 1852s 5s/step - loss: 1.2348
Epoch 7/50
351/351 [==============================] - 1682s 5s/step - loss: 1.2050
Epoch 8/50
351/351 [==============================] - 1823s 5s/step - loss: 1.1812
Epoch 9/50
351/351 [==============================] - 1823s 5s/step - loss: 1.1608
Epoch 10/50
351/351 [==============================] - 1705s 5s/step - loss: 1.1437
Epoch 11/50
351/351 [==============================] - 1822s 5s/step - loss: 1.1283
Epoch 12/50
351/351 [==============================] - 1884s 5s/step - loss: 1.1136
E

# Generating Text

In [ ]:
pwd

In [ ]:
model.save('my_shakespeare_gen.h5') 

In [ ]:
os.chdir()

In [ ]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

model.load_weights('my_shakespeare_gen.h5')

model.build(tf.TensorShape([1, None]))

In [ ]:
model.summary()

In [ ]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
  '''
  model: Trained Model to Generate Text
  start_seed: Intial Seed text in string form
  gen_size: Number of characters to generate

  Basic idea behind this function is to take in some seed text, format it so
  that it is in the correct shape for our network, then loop the sequence as
  we keep adding our own predicted characters. Similar to our work in the RNN
  time series problems.
  '''

  # Number of characters to generate
  num_generate = gen_size

  # Vecotrizing starting seed text
  input_eval = [char_to_ind[s] for s in start_seed]

  # Expand to match batch format shape
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty list to hold resulting generated text
  text_generated = []

  # Temperature effects randomness in our resulting text
  # The term is derived from entropy/thermodynamics.
  # The temperature is used to effect probability of next characters.
  # Higher probability == lesss surprising/ more expected
  # Lower temperature == more surprising / less expected
 
  temperature = temp

  # Here batch size == 1
  model.reset_states()

  for i in range(num_generate):

      # Generate Predictions
      predictions = model(input_eval)

      # Remove the batch shape dimension
      predictions = tf.squeeze(predictions, 0)

      # Use a cateogircal disitribution to select the next character
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # Pass the predicted charracter for the next input
      input_eval = tf.expand_dims([predicted_id], 0)

      # Transform back to character letter
      text_generated.append(ind_to_char[predicted_id])

  return (start_seed + ''.join(text_generated))

In [ ]:
# also try JULIET

print(generate_text(model,"flower",gen_size=1000))

In [ ]:
print(generate_text(model,"JULIET",gen_size=1000))