In [1]:
import pandas as pd
import os

In [2]:
os.getcwd()

'/Users/Bryan/Documents/Programming/pythonNLP/UPDATED_NLP_COURSE/05-Topic-Modeling'

In [3]:
npr = pd.read_csv('npr.csv')
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [4]:
# get a better look

npr['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [5]:
len(npr)

11992

In [6]:
# preprocessing prior to lda

from sklearn.feature_extraction.text import CountVectorizer

In [27]:
# max_df - discard words that show up in x percent of documents has a scale 0 - 1
# min_df - is the opposite, minimum frequency can be a percent or raw number of documents

cv = CountVectorizer(max_df = 0.95, min_df=2, stop_words='english')

In [28]:
dtm = cv.fit_transform(npr['Article'])

In [29]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [30]:
from sklearn.decomposition import LatentDirichletAllocation

In [31]:
LDA = LatentDirichletAllocation(n_components=7, random_state=42)

In [32]:
LDA.fit(dtm)

/Users/Bryan/anaconda/lib/python3.6/site-packages/sklearn/decomposition/online_lda.py:536: DeprecationWarning: The default value for 'learning_method' will be changed from 'online' to 'batch' in the release 0.20. This warning was introduced in 0.18.
  DeprecationWarning)


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7, learning_method=None,
             learning_offset=10.0, max_doc_update_iter=100, max_iter=10,
             mean_change_tol=0.001, n_components=7, n_jobs=1,
             n_topics=None, perp_tol=0.1, random_state=42,
             topic_word_prior=None, total_samples=1000000.0, verbose=0)

In [33]:
# grab the vocabulary of words
len(cv.get_feature_names())


54777

In [34]:
import random

random_word_id = random.randint(0,54777)

cv.get_feature_names()[10]

'01'

In [35]:
# get the topics

In [36]:
len(LDA.components_)

7

In [37]:
type(LDA.components_)

numpy.ndarray

In [38]:
LDA.components_.shape

(7, 54777)

In [39]:
single_topic = LDA.components_[0]

In [40]:
# returns index positions

single_topic.argsort()

array([49163, 21347, 20789, ..., 37374, 42993, 42561])

In [41]:
# get the highest probability words per topic

In [42]:
# get the index positions
# get the top 10 values (10 largest)
# get the last 10 values of argsort

single_topic.argsort()[-10:]

array([ 9511, 49613, 53019, 11657, 21228, 40955, 36283, 37374, 42993,
       42561])

In [43]:
top_twenty_words = single_topic.argsort()[-20:]

In [44]:
for index in top_twenty_words:
    print(cv.get_feature_names()[index])

international
say
years
npr
reported
state
attack
killed
according
military
city
told
war
country
government
reports
people
police
says
said


In [45]:
# print the top words for the topics
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['state', 'attack', 'killed', 'according', 'military', 'city', 'told', 'war', 'country', 'government', 'reports', 'people', 'police', 'says', 'said']


THE TOP 15 WORDS FOR TOPIC #1
['russian', 'npr', 'fbi', 'did', 'clinton', 'told', 'media', 'white', 'campaign', 'russia', 'house', 'news', 'president', 'said', 'trump']


THE TOP 15 WORDS FOR TOPIC #2
['world', 'year', 'make', 'day', 'home', 'time', 'city', 'new', 'years', 'just', 'people', 'water', 'like', 'food', 'says']


THE TOP 15 WORDS FOR TOPIC #3
['women', 'don', 'just', 'research', 'like', 'university', 'children', 'percent', 'care', 'study', 'students', 'school', 'health', 'people', 'says']


THE TOP 15 WORDS FOR TOPIC #4
['vote', 'court', 'new', 'percent', 'republican', 'law', 'campaign', 'obama', 'states', 'people', 'president', 'clinton', 'state', 'said', 'trump']


THE TOP 15 WORDS FOR TOPIC #5
['ve', 'going', 'years', 'don', 'life', 'new', 'really', 'way', 'says', 'know', 'think', 'time', 'pe

In [46]:
topic_results = LDA.transform(dtm)

In [47]:
topic_results

array([[7.31632607e-02, 6.75553233e-01, 6.25535235e-03, ...,
        2.21208569e-01, 2.25552570e-04, 2.33684623e-02],
       [2.35125805e-01, 4.64538191e-01, 4.40624067e-04, ...,
        1.43668858e-01, 4.41231052e-04, 1.55344712e-01],
       [4.36734669e-02, 7.93952676e-01, 3.28586091e-04, ...,
        1.61059142e-01, 3.28574132e-04, 3.29268386e-04],
       ...,
       [2.23336461e-01, 3.98657469e-04, 2.31603557e-01, ...,
        3.10766862e-02, 1.35312300e-01, 1.51623533e-02],
       [4.33700550e-04, 1.38658343e-01, 4.33017976e-04, ...,
        7.49398998e-01, 1.10210327e-01, 4.32759896e-04],
       [1.68066870e-01, 2.54141079e-04, 2.20598993e-01, ...,
        2.91258806e-01, 1.28635434e-01, 1.77571613e-01]])

In [48]:
topic_results.shape

(11992, 7)

In [50]:
topic_results[0].round(2)

array([0.07, 0.68, 0.01, 0.  , 0.22, 0.  , 0.02])

In [51]:
# get index position of highest probability

topic_results[0].argmax()

1

In [52]:
npr['Topic'] = topic_results.argmax(axis=1)

In [53]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      5
5      I did not want to join yoga class. I hated tho...      3
6      With a   who has publicly supported the debunk...      3
7      I was standing by the airport exit, debating w...      2
8      If movies were trying to be more realistic, pe...      2
9      Eighteen years ago, on New Year’s Eve, David F...      2
10     For years now, some of the best, wildest, most...      5
11     For years now, some of the best, wildest, most...      5
12     The Colorado River is like a giant bank accoun...      2
13     For the last installment of NPR’s holiday reci...      2
14     Being overweight can raise your blood pressure...      3
15     Who’s the YouTube star of 2016? Adele singing ...      5
16     Here’s a quick roundup of some of the   you ma...      5
17     Ben Johnston doesn’t follow the rules of music...      5
18     David Bowie, Prince and George Michael are all...      5
19     In November, the typically straitlaced Office ...      1
20     This is the time of year when everybody is mak...      5
21     Terrorist attacks, hurricanes, a divisive U. S...      5
22     We all experience stress at work, no matter th...      3
23     When John Fahey recorded The New Possibility i...      5
24     This year was one of   hacks, exploding smartp...      5
25     From West Virginia to Wyoming, coal country ov...      6
26     Updated Jan. 1 at 9:56 a. m. ET, At least 39 p...      0
27     On the morning of Jan. 1, Los Angeles resident...      0
28     In September, reproductive endocrinologist Joh...      3
29     In an effort to take advantage of the intimate...      3
...                                                  ...    ...
11962  Updated at 6:15 p. m. The White House has anno...      1
11963  The actress Debbie Reynolds’ death just one da...      3
11964  Here’s a timely reminder for all you   reveler...      6
11965  Every year in late November, the New Mexican v...      2
11966  Time to get together the transcripts and the t...      3
11967  Hollywood is in the process of closing out a  ...      5
11968  Dealing with a flood of   pardon requests amou...      1
11969  Rashaan Salaam, the former college football st...      3
11970  On the top of Hawaii’s Mauna Kea mountain Thur...      6
11971  A tiny pink peanut is not a white rhinoceros. ...      2
11972  In a disappointment to Alzheimer’s patients an...      3
11973  In my early 20s, smitten by the mythic underpi...      5
11974  It’s been a lively year for social media maven...      0
11975  This is not a review. It started out as one: I...      5
11976  On a summer’s day in December, a warehouse in ...      2
11977  Elections aren’t exactly cozy, even in the bes...      5
11978  Although her oldest child, Ben, is 10 years ol...      3
11979  When a political scandal explodes in France, t...      0
11980  The darkest moment for American police this ye...      0
11981  Russia was ordered to vacate two compounds it ...      1
11982  A North Carolina judge is temporarily blocking...      4
11983  China’s police are under fire this week as cit...      0
11984  Before the virus overwhelmed Puerto Rico, Zika...      3
11985  It seems everything today has a flavor wheel, ...      2
11986  In the final days of a year that has become kn...      2
11987  The number of law enforcement officers shot an...      0
11988    Trump is busy these days with victory tours,...      1
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      4

[11992 rows x 2 columns]

# Non Negative Matrix Factorization (NNMF)

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [55]:
# use tfidf

tfidf = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [56]:
dtm2 = tfidf.fit_transform(npr['Article'])

In [57]:
dtm2

<11992x54777 sparse matrix of type '<class 'numpy.float64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [58]:
from sklearn.decomposition import NMF

In [59]:
nmf_model = NMF(n_components=7,random_state=42)

In [74]:
# This can take awhile, we're dealing with a large amount of documents!
nmf_model.fit(dtm2)

NMF(alpha=0.0, beta_loss='frobenius', init=None, l1_ratio=0.0, max_iter=200,
  n_components=7, random_state=42, shuffle=False, solver='cd', tol=0.0001,
  verbose=0)

In [75]:
len(tfidf.get_feature_names())

54777

In [76]:
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(tfidf.get_feature_names()[random_word_id])

extreme
admiral
candies
prospero
barley
gagnon
loathsome
namibia
leader
greenwood


In [77]:
len(nmf_model.components_)

7

In [78]:
nmf_model.components_

array([[0.00000000e+00, 2.49950821e-01, 0.00000000e+00, ...,
        1.70313822e-03, 2.37544362e-04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 8.22048918e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 3.12379960e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.89723338e-03, 0.00000000e+00, 1.50186440e-03, ...,
        7.06428924e-04, 5.85500542e-04, 6.89536542e-04],
       [4.01763234e-03, 5.31643833e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [79]:
len(nmf_model.components_[0])

54777

In [80]:
single_topic = nmf_model.components_[0]

In [81]:
# Returns the indices that would sort this array.
single_topic.argsort()

array([    0, 27208, 27206, ..., 36283, 54692, 42993])

In [82]:
# Word least representative of this topic
single_topic[42993]

2.005055165418594

In [83]:
# Word most representative of this topic
single_topic[28659]

0.2811348713172735

In [84]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([14441, 36310, 53989, 52615, 47218, 53152, 19307, 36283, 54692,
       42993])

In [85]:
top_word_indices = single_topic.argsort()[-10:]

In [86]:
for index in top_word_indices:
    print(tfidf.get_feature_names()[index])

disease
percent
women
virus
study
water
food
people
zika
says


In [87]:
for index,topic in enumerate(nmf_model.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([tfidf.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']


THE TOP 15 WORDS FOR TOPIC #1
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


THE TOP 15 WORDS FOR TOPIC #2
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


THE TOP 15 WORDS FOR TOPIC #3
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


THE TOP 15 WORDS FOR TOPIC #4
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


THE TOP 15 WORDS FOR TOPIC #5
['love', 've', 'don', 'al

In [88]:
topic_results = nmf_model.transform(dtm2)

In [89]:
topic_results.shape

(11992, 7)

In [90]:
topic_results[0].round(2)

array([0.  , 0.12, 0.  , 0.06, 0.02, 0.  , 0.  ])

In [91]:
topic_results[0].argmax()

1

In [92]:
npr['Topic'] = topic_results.argmax(axis=1)

In [93]:
npr.head(10)

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      3
4  From photography, illustration and video, to d...      6
5  I did not want to join yoga class. I hated tho...      5
6  With a   who has publicly supported the debunk...      0
7  I was standing by the airport exit, debating w...      0
8  If movies were trying to be more realistic, pe...      0
9  Eighteen years ago, on New Year’s Eve, David F...      5

In [94]:
# map with words

mytopic_dict = {0:'health',1:'election',2:'legistature',3:'politics',4:'election',5:'music',6:'edu'}

npr['Topic Label'] = npr['Topic'].map(mytopic_dict)


In [96]:
npr

Article  Topic  Topic Label
0      In the Washington of 2016, even when the polic...      1     election
1        Donald Trump has used Twitter  —   his prefe...      1     election
2        Donald Trump is unabashedly praising Russian...      1     election
3      Updated at 2:50 p. m. ET, Russian President Vl...      3     politics
4      From photography, illustration and video, to d...      6          edu
5      I did not want to join yoga class. I hated tho...      5        music
6      With a   who has publicly supported the debunk...      0       health
7      I was standing by the airport exit, debating w...      0       health
8      If movies were trying to be more realistic, pe...      0       health
9      Eighteen years ago, on New Year’s Eve, David F...      5        music
10     For years now, some of the best, wildest, most...      5        music
11     For years now, some of the best, wildest, most...      5        music
12     The Colorado River is like a giant bank accoun...      0       health
13     For the last installment of NPR’s holiday reci...      5        music
14     Being overweight can raise your blood pressure...      0       health
15     Who’s the YouTube star of 2016? Adele singing ...      5        music
16     Here’s a quick roundup of some of the   you ma...      3     politics
17     Ben Johnston doesn’t follow the rules of music...      5        music
18     David Bowie, Prince and George Michael are all...      5        music
19     In November, the typically straitlaced Office ...      1     election
20     This is the time of year when everybody is mak...      5        music
21     Terrorist attacks, hurricanes, a divisive U. S...      5        music
22     We all experience stress at work, no matter th...      6          edu
23     When John Fahey recorded The New Possibility i...      5        music
24     This year was one of   hacks, exploding smartp...      5        music
25     From West Virginia to Wyoming, coal country ov...      1     election
26     Updated Jan. 1 at 9:56 a. m. ET, At least 39 p...      3     politics
27     On the morning of Jan. 1, Los Angeles resident...      3     politics
28     In September, reproductive endocrinologist Joh...      0       health
29     In an effort to take advantage of the intimate...      0       health
...                                                  ...    ...          ...
11962  Updated at 6:15 p. m. The White House has anno...      3     politics
11963  The actress Debbie Reynolds’ death just one da...      0       health
11964  Here’s a timely reminder for all you   reveler...      5        music
11965  Every year in late November, the New Mexican v...      5        music
11966  Time to get together the transcripts and the t...      6          edu
11967  Hollywood is in the process of closing out a  ...      5        music
11968  Dealing with a flood of   pardon requests amou...      3     politics
11969  Rashaan Salaam, the former college football st...      5        music
11970  On the top of Hawaii’s Mauna Kea mountain Thur...      0       health
11971  A tiny pink peanut is not a white rhinoceros. ...      0       health
11972  In a disappointment to Alzheimer’s patients an...      0       health
11973  In my early 20s, smitten by the mythic underpi...      5        music
11974  It’s been a lively year for social media maven...      3     politics
11975  This is not a review. It started out as one: I...      5        music
11976  On a summer’s day in December, a warehouse in ...      5        music
11977  Elections aren’t exactly cozy, even in the bes...      4     election
11978  Although her oldest child, Ben, is 10 years ol...      0       health
11979  When a political scandal explodes in France, t...      0       health
11980  The darkest moment for American police this ye...      3     politics
11981  Russia was ordered to vacate two compounds it ...      3     politics
11982  A North Carolina judge is temporarily 